matrix:
  include:
    - language: python
      python: 
        - 3.6
      before_install:
        - cd backend/
      install: 
        - pip install -e .
      script:
        - pytest

    - language: php
      php:
        - 7.2

notifications:
  email: false